version: '3.8'

services:
  cv-app-dev:
    image: node:20-alpine
    container_name: cv_dani_dev
    working_dir: /app
    volumes:
      - ./cv:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
  app:
    build: .
    container_name: cvdani-prueba
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development

