version: '3.8'

services:
  cv-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv_dani_container
    ports:
      - "3000:80"   # Mapea el puerto 3000 de tu Ubuntu al puerto 80 de Nginx
    restart: always